# Generated by Django 4.2.14 on 2025-09-05 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('video', '비디오'), ('file', '파일'), ('system', '시스템 메시지')], default='text', max_length=20, verbose_name='메시지 유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('is_edited', models.BooleanField(default=False, verbose_name='수정됨')),
                ('is_system', models.BooleanField(default=False, verbose_name='시스템 메시지')),
                ('notion_synced', models.BooleanField(default=False, verbose_name='Notion 동기화됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedbackmessage', verbose_name='부모 메시지')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
            options={
                'verbose_name': '피드백 메시지',
                'verbose_name_plural': '피드백 메시지들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('thread_type', models.CharField(choices=[('task_feedback', '업무 피드백'), ('report_feedback', '보고서 피드백'), ('general_feedback', '일반 피드백'), ('urgent_feedback', '긴급 피드백')], default='general_feedback', max_length=20, verbose_name='피드백 유형')),
                ('status', models.CharField(choices=[('active', '활성'), ('resolved', '해결됨'), ('closed', '종료됨'), ('archived', '보관됨')], default='active', max_length=20, verbose_name='상태')),
                ('notion_page_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notion 페이지 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='마지막 활동일시')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_threads', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '피드백 스레드',
                'verbose_name_plural': '피드백 스레드들',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('partner', '파트너'), ('observer', '참관자')], default='partner', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스레드 참여자',
                'verbose_name_plural': '스레드 참여자들',
                'unique_together': {('thread', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='feedback/media/%Y/%m/', verbose_name='파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('media_type', models.CharField(choices=[('image', '이미지'), ('video', '비디오'), ('document', '문서'), ('audio', '오디오'), ('other', '기타')], max_length=20, verbose_name='미디어 유형')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='가로 크기')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='세로 크기')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='재생 시간 (초)')),
                ('is_compressed', models.BooleanField(default=False, verbose_name='압축됨')),
                ('compression_level', models.CharField(choices=[('none', '압축 없음'), ('low', '낮은 압축'), ('medium', '중간 압축'), ('high', '높은 압축')], default='none', max_length=20, verbose_name='압축 레벨')),
                ('original_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='원본 파일 크기')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='feedback/thumbnails/%Y/%m/', verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackmessage', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '미디어 첨부파일',
                'verbose_name_plural': '미디어 첨부파일들',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackthread',
            name='participants',
            field=models.ManyToManyField(related_name='feedback_threads', through='feedback.ThreadParticipant', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
        migrations.CreateModel(
            name='FeedbackNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', '새 메시지'), ('thread_created', '스레드 생성됨'), ('thread_resolved', '스레드 해결됨'), ('mention', '언급됨'), ('assignment', '할당됨')], max_length=20, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='feedback.feedbackmessage', verbose_name='메시지')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='feedback.feedbackthread', verbose_name='스레드')),
            ],
            options={
                'verbose_name': '피드백 알림',
                'verbose_name_plural': '피드백 알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feedback.feedbackthread', verbose_name='스레드'),
        ),
    ]
