# Generated by Django 4.2.14 on 2025-09-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('color', models.CharField(default='#3788d8', help_text='HEX 색상 코드', max_length=7, verbose_name='색상')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('accessible_user_types', models.JSONField(default=list, help_text='["SUPER_ADMIN", "MANAGER"] 형태로 저장', verbose_name='접근 가능한 사용자 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '캘린더 카테고리',
                'verbose_name_plural': '캘린더 카테고리들',
                'db_table': 'calendar_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_datetime', models.DateTimeField(verbose_name='시작일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료일시')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='종일 일정')),
                ('event_type', models.CharField(choices=[('meeting', '회의'), ('deadline', '마감일'), ('vacation', '휴가'), ('work', '업무'), ('personal', '개인'), ('company', '회사')], default='work', max_length=20, verbose_name='이벤트 타입')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('urgent', '긴급')], default='medium', max_length=10, verbose_name='우선순위')),
                ('recurrence_type', models.CharField(choices=[('none', '반복 없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], default='none', max_length=10, verbose_name='반복 타입')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='반복 종료일')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('url', models.URLField(blank=True, verbose_name='관련 URL')),
                ('reminder_minutes', models.IntegerField(default=15, help_text='이벤트 시작 몇 분 전에 알림을 받을지', verbose_name='알림 시간(분 전)')),
                ('notion_page_id', models.CharField(blank=True, max_length=100, verbose_name='Notion 페이지 ID')),
                ('notion_database_id', models.CharField(blank=True, max_length=100, verbose_name='Notion 데이터베이스 ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '캘린더 이벤트',
                'verbose_name_plural': '캘린더 이벤트들',
                'db_table': 'calendar_event',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='NotionCalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제'), ('sync', '동기화')], max_length=10, verbose_name='동기화 타입')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('notion_page_id', models.CharField(blank=True, max_length=100, verbose_name='Notion 페이지 ID')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='요청 데이터')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='응답 데이터')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='실행일시')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True, verbose_name='실행 시간(ms)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='calendar_system.calendarevent', verbose_name='이벤트')),
            ],
            options={
                'verbose_name': 'Notion 동기화 로그',
                'verbose_name_plural': 'Notion 동기화 로그들',
                'db_table': 'calendar_notion_sync',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('accepted', '참석'), ('declined', '불참'), ('tentative', '미정')], default='pending', max_length=10, verbose_name='참석 상태')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='응답일시')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_system.calendarevent', verbose_name='이벤트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
            ],
            options={
                'verbose_name': '이벤트 참석자',
                'verbose_name_plural': '이벤트 참석자들',
                'db_table': 'calendar_event_attendee',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('dayGridMonth', '월'), ('timeGridWeek', '주'), ('timeGridDay', '일'), ('listWeek', '목록')], default='dayGridMonth', max_length=20, verbose_name='기본 보기')),
                ('work_start_time', models.TimeField(default='09:00', verbose_name='업무 시작 시간')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='업무 종료 시간')),
                ('default_reminder_minutes', models.IntegerField(default=15, verbose_name='기본 알림 시간(분)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('show_weekends', models.BooleanField(default=True, verbose_name='주말 표시')),
                ('show_declined_events', models.BooleanField(default=False, verbose_name='거절한 일정 표시')),
                ('visible_categories', models.JSONField(default=list, help_text='카테고리 ID 배열', verbose_name='표시할 카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캘린더 설정',
                'verbose_name_plural': '캘린더 설정들',
                'db_table': 'calendar_settings',
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_events', through='calendar_system.EventAttendee', to=settings.AUTH_USER_MODEL, verbose_name='참석자'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_system.calendarcategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_datetime', models.DateTimeField(verbose_name='알림 시간')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('sent', '발송됨'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('notification_method', models.CharField(default='push', help_text='push, email, sms 등', max_length=20, verbose_name='알림 방법')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_system.calendarevent', verbose_name='이벤트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이벤트 알림',
                'verbose_name_plural': '이벤트 알림들',
                'db_table': 'calendar_event_reminder',
                'unique_together': {('event', 'user', 'reminder_datetime')},
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='calendar_ev_start_d_f7a069_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['creator', 'is_active'], name='calendar_ev_creator_dd11fc_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['category', 'event_type'], name='calendar_ev_categor_871f84_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['notion_page_id'], name='calendar_ev_notion__5f5fb5_idx'),
        ),
    ]
