# Generated by Django 4.2.14 on 2025-09-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('report_type', models.CharField(choices=[('daily', '일일보고'), ('incident', '사고/이슈'), ('inspection', '점검보고'), ('progress', '진행상황'), ('completion', '완료보고'), ('other', '기타')], default='daily', max_length=20, verbose_name='보고 유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출일시')),
                ('project_name', models.CharField(max_length=100, verbose_name='프로젝트명')),
                ('site_name', models.CharField(max_length=100, verbose_name='현장명')),
                ('contractor', models.CharField(blank=True, max_length=100, verbose_name='도급사')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='경도')),
                ('location_address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '제출완료'), ('synced', '동기화완료'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=20, verbose_name='상태')),
                ('is_offline', models.BooleanField(default=False, verbose_name='오프라인 작성')),
                ('sync_status', models.CharField(blank=True, max_length=50, verbose_name='동기화 상태')),
                ('weather', models.CharField(blank=True, max_length=50, verbose_name='날씨')),
                ('temperature', models.CharField(blank=True, max_length=20, verbose_name='온도')),
                ('workers_count', models.IntegerField(default=0, verbose_name='작업인원')),
                ('attendees', models.TextField(blank=True, verbose_name='참석자 명단')),
                ('review_comment', models.TextField(blank=True, verbose_name='검토 의견')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('notion_page_id', models.CharField(blank=True, max_length=100, verbose_name='Notion 페이지 ID')),
                ('notion_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Notion 동기화 시간')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 데이터')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '현장 리포트',
                'verbose_name_plural': '현장 리포트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='field_reports/%Y/%m/%d/', verbose_name='파일')),
                ('file_type', models.CharField(choices=[('image', '이미지'), ('document', '문서'), ('video', '동영상'), ('audio', '음성'), ('other', '기타')], default='image', max_length=20, verbose_name='파일 유형')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='field_reports/thumbnails/%Y/%m/%d/', verbose_name='썸네일')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('is_synced', models.BooleanField(default=False, verbose_name='동기화 여부')),
                ('exif_data', models.JSONField(blank=True, default=dict, verbose_name='EXIF 데이터')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='field_reports.fieldreport', verbose_name='리포트')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
