# Generated by Django 4.2.14 on 2025-09-06 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='검색어')),
                ('count', models.IntegerField(default=1, verbose_name='검색 횟수')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='마지막 검색')),
                ('daily_count', models.IntegerField(default=0)),
                ('weekly_count', models.IntegerField(default=0)),
                ('monthly_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '인기 검색어',
                'verbose_name_plural': '인기 검색어',
                'ordering': ['-count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='키워드')),
                ('suggestion', models.CharField(max_length=255, verbose_name='제안어')),
                ('weight', models.FloatField(default=1.0, verbose_name='가중치')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('category', models.CharField(choices=[('general', '일반'), ('report', '리포트'), ('user', '사용자'), ('location', '위치'), ('tag', '태그')], default='general', max_length=50)),
            ],
            options={
                'verbose_name': '검색 제안',
                'verbose_name_plural': '검색 제안',
                'ordering': ['-weight', '-usage_count'],
                'indexes': [models.Index(fields=['keyword', 'category'], name='search_sear_keyword_4c060d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('search_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '검색 인덱스',
                'verbose_name_plural': '검색 인덱스',
                'ordering': ['-search_weight', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='search_sear_content_97a989_idx'), models.Index(fields=['author', 'category'], name='search_sear_author__aac09f_idx'), models.Index(fields=['created_at'], name='search_sear_created_160fb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='검색어')),
                ('results_count', models.IntegerField(default=0, verbose_name='결과 수')),
                ('search_type', models.CharField(choices=[('all', '전체'), ('reports', '리포트'), ('comments', '댓글'), ('users', '사용자'), ('activities', '활동')], default='all', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색 기록',
                'verbose_name_plural': '검색 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_sear_user_id_71e095_idx'), models.Index(fields=['query'], name='search_sear_query_d8a8e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='필터 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='검색어')),
                ('filters', models.JSONField(default=dict, verbose_name='필터 조건')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 필터')),
                ('is_shared', models.BooleanField(default=False, verbose_name='공유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '저장된 검색',
                'verbose_name_plural': '저장된 검색',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
