# Generated by Django 5.0 on 2025-01-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.CharField(db_index=True, help_text='Notion 데이터베이스 고유 ID', max_length=36, unique=True, verbose_name='Notion ID')),
                ('title', models.CharField(help_text='데이터베이스 제목', max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, help_text='데이터베이스 설명', verbose_name='설명')),
                ('database_type', models.CharField(choices=[('tasks', '작업 관리'), ('calendar', '캘린더'), ('reports', '리포트'), ('users', '사용자 관리'), ('sales', '매출 관리'), ('custom', '커스텀')], default='custom', help_text='데이터베이스 유형', max_length=20, verbose_name='데이터베이스 타입')),
                ('schema', models.JSONField(default=dict, help_text='Notion 데이터베이스 스키마 정보', verbose_name='스키마')),
                ('is_active', models.BooleanField(default=True, help_text='동기화 활성화 여부', verbose_name='활성 상태')),
                ('sync_interval', models.IntegerField(default=300, help_text='동기화 간격 (초 단위)', verbose_name='동기화 간격')),
                ('last_synced', models.DateTimeField(blank=True, help_text='마지막 동기화 시간', null=True, verbose_name='마지막 동기화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(help_text='데이터베이스를 등록한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='created_databases', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': 'Notion 데이터베이스',
                'verbose_name_plural': 'Notion 데이터베이스',
                'db_table': 'notion_databases',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.CharField(db_index=True, help_text='Notion 페이지 고유 ID', max_length=36, verbose_name='Notion 페이지 ID')),
                ('title', models.CharField(help_text='페이지 제목', max_length=500, verbose_name='제목')),
                ('status', models.CharField(choices=[('active', '활성'), ('archived', '보관'), ('deleted', '삭제')], default='active', help_text='페이지 상태', max_length=20, verbose_name='상태')),
                ('properties', models.JSONField(default=dict, help_text='페이지 속성 데이터', verbose_name='속성')),
                ('content_blocks', models.JSONField(blank=True, default=list, help_text='페이지 콘텐츠 블록', null=True, verbose_name='콘텐츠')),
                ('notion_created_time', models.DateTimeField(help_text='Notion에서의 생성 시간', verbose_name='Notion 생성일')),
                ('notion_last_edited_time', models.DateTimeField(help_text='Notion에서의 마지막 수정 시간', verbose_name='Notion 수정일')),
                ('notion_created_by', models.CharField(blank=True, help_text='Notion에서 생성한 사용자 ID', max_length=36, null=True, verbose_name='Notion 생성자')),
                ('notion_last_edited_by', models.CharField(blank=True, help_text='Notion에서 마지막 수정한 사용자 ID', max_length=36, null=True, verbose_name='Notion 수정자')),
                ('local_hash', models.CharField(blank=True, help_text='로컬 데이터 해시 (변경 감지용)', max_length=64, null=True, verbose_name='로컬 해시')),
                ('is_dirty', models.BooleanField(default=False, help_text='동기화가 필요한 상태', verbose_name='동기화 필요')),
                ('sync_conflicts', models.JSONField(default=list, help_text='동기화 충돌 내용', verbose_name='동기화 충돌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='로컬 생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='로컬 수정일시')),
                ('database', models.ForeignKey(help_text='소속 데이터베이스', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='notion_api.notiondatabase', verbose_name='데이터베이스')),
            ],
            options={
                'verbose_name': 'Notion 페이지',
                'verbose_name_plural': 'Notion 페이지',
                'db_table': 'notion_pages',
                'ordering': ['-notion_last_edited_time'],
                'unique_together': {('database', 'notion_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, help_text='동기화 작업 고유 ID', unique=True, verbose_name='동기화 ID')),
                ('sync_type', models.CharField(choices=[('manual', '수동 동기화'), ('scheduled', '예약된 동기화'), ('incremental', '증분 동기화'), ('full_sync', '전체 동기화'), ('webhook', '웹훅 동기화')], help_text='동기화 유형', max_length=20, verbose_name='동기화 타입')),
                ('status', models.CharField(choices=[('started', '시작됨'), ('in_progress', '진행 중'), ('completed', '완료됨'), ('failed', '실패함')], default='started', help_text='동기화 상태', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='동기화 시작 시간', verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, help_text='동기화 완료 시간', null=True, verbose_name='완료 시간')),
                ('duration', models.DurationField(blank=True, help_text='동기화 소요 시간', null=True, verbose_name='소요 시간')),
                ('total_pages', models.IntegerField(default=0, help_text='총 처리된 페이지 수', verbose_name='총 페이지 수')),
                ('pages_created', models.IntegerField(default=0, help_text='새로 생성된 페이지 수', verbose_name='생성된 페이지')),
                ('pages_updated', models.IntegerField(default=0, help_text='업데이트된 페이지 수', verbose_name='업데이트된 페이지')),
                ('pages_deleted', models.IntegerField(default=0, help_text='삭제된 페이지 수', verbose_name='삭제된 페이지')),
                ('pages_failed', models.IntegerField(default=0, help_text='실패한 페이지 수', verbose_name='실패한 페이지')),
                ('error_message', models.TextField(blank=True, help_text='오류 메시지', null=True, verbose_name='오류 메시지')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='상세 오류 정보', null=True, verbose_name='상세 오류')),
                ('database', models.ForeignKey(help_text='동기화 대상 데이터베이스', on_delete=django.db.models.deletion.CASCADE, related_name='sync_history', to='notion_api.notiondatabase', verbose_name='데이터베이스')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='동기화를 실행한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
            ],
            options={
                'verbose_name': '동기화 기록',
                'verbose_name_plural': '동기화 기록',
                'db_table': 'sync_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NotionWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(help_text='Notion 웹훅 ID', max_length=100, unique=True, verbose_name='웹훅 ID')),
                ('event_types', models.JSONField(default=list, help_text='감지할 이벤트 타입들', verbose_name='이벤트 타입')),
                ('is_active', models.BooleanField(default=True, help_text='웹훅 활성화 여부', verbose_name='활성 상태')),
                ('total_calls', models.IntegerField(default=0, help_text='총 웹훅 호출 횟수', verbose_name='호출 횟수')),
                ('last_called', models.DateTimeField(blank=True, help_text='마지막 웹훅 호출 시간', null=True, verbose_name='마지막 호출')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('database', models.OneToOneField(help_text='연결된 데이터베이스', on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='notion_api.notiondatabase', verbose_name='데이터베이스')),
            ],
            options={
                'verbose_name': 'Notion 웹훅',
                'verbose_name_plural': 'Notion 웹훅',
                'db_table': 'notion_webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]