# Generated by Django 4.2.14 on 2025-09-07 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('event_type', models.CharField(choices=[('meeting', '회의'), ('task', '작업'), ('deadline', '마감일'), ('reminder', '알림'), ('holiday', '휴일'), ('other', '기타')], default='meeting', max_length=20, verbose_name='이벤트 유형')),
                ('start_date', models.DateTimeField(verbose_name='시작 일시')),
                ('end_date', models.DateTimeField(verbose_name='종료 일시')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일 이벤트')),
                ('repeat', models.CharField(choices=[('none', '반복 없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], default='none', max_length=20, verbose_name='반복')),
                ('repeat_until', models.DateField(blank=True, null=True, verbose_name='반복 종료일')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='위치')),
                ('reminder_minutes', models.IntegerField(default=15, verbose_name='알림 시간(분)')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='색상')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='주최자')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
            ],
            options={
                'verbose_name': '캘린더 이벤트',
                'verbose_name_plural': '캘린더 이벤트',
                'ordering': ['start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_date', 'end_date'], name='dashboard_c_start_d_2911ef_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organizer', 'start_date'], name='dashboard_c_organiz_ab6450_idx'),
        ),
    ]
