# Generated by Django 4.2.14 on 2025-09-05 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_company_holiday', models.BooleanField(default=False)),
                ('is_public_holiday', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('notion_page_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '휴일',
                'verbose_name_plural': '휴일들',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('annual', '연차'), ('sick', '병가'), ('special', '특별휴가'), ('half_day', '반차'), ('replacement', '대체휴무')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '연차 유형',
                'verbose_name_plural': '연차 유형들',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day_start', models.BooleanField(default=False)),
                ('is_half_day_end', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('emergency_contact', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '반려됨'), ('cancelled', '취소됨')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('total_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('notion_page_id', models.CharField(blank=True, max_length=255)),
                ('notion_sync_status', models.CharField(default='pending', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_offline_created', models.BooleanField(default=False)),
                ('offline_sync_data', models.JSONField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_management.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '연차 신청',
                'verbose_name_plural': '연차 신청들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='leave_manag_user_id_c92ab8_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_manag_start_d_903b4d_idx'), models.Index(fields=['approver', 'status'], name='leave_manag_approve_d04fea_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('total_annual_days', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('used_annual_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('remaining_annual_days', models.DecimalField(decimal_places=1, default=15.0, max_digits=5)),
                ('carry_over_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('notion_database_id', models.CharField(blank=True, max_length=255)),
                ('notion_sync_status', models.CharField(default='pending', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '연차 잔여일수',
                'verbose_name_plural': '연차 잔여일수',
                'unique_together': {('user', 'year')},
            },
        ),
    ]
