# Generated by Django 4.2.14 on 2025-09-05 06:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='설정 이름', max_length=100)),
                ('description', models.TextField(blank=True, help_text='설정 설명')),
                ('setting_type', models.CharField(choices=[('legal', '법정 근로시간'), ('company', '회사 규정'), ('department', '부서 규정'), ('individual', '개인 규정')], default='company', max_length=20)),
                ('daily_standard_minutes', models.IntegerField(default=480, help_text='일 표준 근무시간 (분)')),
                ('weekly_standard_minutes', models.IntegerField(default=2400, help_text='주 표준 근무시간 (분)')),
                ('monthly_standard_minutes', models.IntegerField(default=10400, help_text='월 표준 근무시간 (분)')),
                ('early_arrival_limit_minutes', models.IntegerField(default=60, help_text='조기출근 허용시간 (분)')),
                ('late_departure_limit_minutes', models.IntegerField(default=180, help_text='늦은퇴근 허용시간 (분)')),
                ('break_time_minutes', models.IntegerField(default=60, help_text='휴게시간 (분)')),
                ('auto_deduct_break', models.BooleanField(default=True, help_text='휴게시간 자동 차감 여부')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='적용 시작일')),
                ('effective_until', models.DateField(blank=True, help_text='적용 종료일', null=True)),
                ('notion_database_id', models.CharField(blank=True, help_text='Notion 데이터베이스 ID', max_length=36)),
                ('notion_page_id', models.CharField(blank=True, help_text='Notion 페이지 ID', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_settings', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text='적용 대상 사용자', related_name='work_time_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '근무시간 설정',
                'verbose_name_plural': '근무시간 설정 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('daily', '일일 초과근무'), ('weekly', '주간 초과근무'), ('holiday', '휴일근무'), ('night', '야간근무')], max_length=20)),
                ('threshold_minutes', models.IntegerField(help_text='초과근무 기준시간 (분)')),
                ('pay_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='수당 비율 (1.5 = 150%)', max_digits=5)),
                ('requires_approval', models.BooleanField(default=True, help_text='사전 승인 필요 여부')),
                ('max_overtime_minutes', models.IntegerField(default=180, help_text='최대 초과근무 시간 (분)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='overtime_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '초과근무 규정',
                'verbose_name_plural': '초과근무 규정 목록',
            },
        ),
        migrations.CreateModel(
            name='WorkTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간'), ('yearly', '연간')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('total_work_minutes', models.IntegerField(default=0)),
                ('actual_work_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('standard_work_minutes', models.IntegerField(default=0)),
                ('work_days', models.IntegerField(default=0, help_text='실제 출근일수')),
                ('expected_work_days', models.IntegerField(default=0, help_text='예상 출근일수')),
                ('late_count', models.IntegerField(default=0, help_text='지각 횟수')),
                ('early_leave_count', models.IntegerField(default=0, help_text='조퇴 횟수')),
                ('notion_page_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '근무시간 요약',
                'verbose_name_plural': '근무시간 요약 목록',
                'indexes': [models.Index(fields=['user', 'summary_type', 'year', 'month'], name='time_manage_user_id_d12e40_idx'), models.Index(fields=['updated_at'], name='time_manage_updated_01059a_idx')],
                'unique_together': {('user', 'summary_type', 'year', 'month', 'week', 'day')},
            },
        ),
        migrations.CreateModel(
            name='WorkTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='근무일')),
                ('record_type', models.CharField(choices=[('normal', '일반 근무'), ('overtime', '초과 근무'), ('holiday', '휴일 근무'), ('night', '야간 근무'), ('remote', '재택 근무')], default='normal', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='출근 시간', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='퇴근 시간', null=True)),
                ('total_work_minutes', models.IntegerField(default=0, help_text='총 근무시간 (분)')),
                ('break_minutes', models.IntegerField(default=0, help_text='휴게시간 (분)')),
                ('actual_work_minutes', models.IntegerField(default=0, help_text='실제 근무시간 (분, 휴게시간 제외)')),
                ('overtime_minutes', models.IntegerField(default=0, help_text='초과 근무시간 (분)')),
                ('check_in_location', models.JSONField(blank=True, default=dict, help_text='출근 위치 정보 (GPS 좌표 등)')),
                ('check_out_location', models.JSONField(blank=True, default=dict, help_text='퇴근 위치 정보 (GPS 좌표 등)')),
                ('memo', models.TextField(blank=True, help_text='메모')),
                ('adjustment_reason', models.TextField(blank=True, help_text='시간 조정 사유')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('confirmed', '확정'), ('approved', '승인됨'), ('rejected', '반려됨'), ('modified', '수정됨')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='승인 시간', null=True)),
                ('notion_page_id', models.CharField(blank=True, help_text='Notion 페이지 ID', max_length=36)),
                ('notion_last_synced', models.DateTimeField(blank=True, help_text='Notion 마지막 동기화 시간', null=True)),
                ('is_notion_synced', models.BooleanField(default=False, help_text='Notion 동기화 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='승인자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='work_time_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '근무시간 기록',
                'verbose_name_plural': '근무시간 기록 목록',
                'ordering': ['-work_date', '-check_in_time'],
                'indexes': [models.Index(fields=['user', 'work_date'], name='time_manage_user_id_ad1540_idx'), models.Index(fields=['work_date', 'status'], name='time_manage_work_da_7ac35a_idx'), models.Index(fields=['is_notion_synced'], name='time_manage_is_noti_e3cd4d_idx')],
                'unique_together': {('user', 'work_date')},
            },
        ),
    ]
